[BuildRules]  Fixed qoutation for compile_commands.json
Use correct quotations e.g.
```
-DPROJECT_NAME='\"CMSSW\"'
```
instead of
```
-DPROJECT_NAME=\"CMSSW\"
```
to avoid compilation errors during code-checks
```
L1MuGMTParametersOnlineProducer.cc:118:65: error: expected ')' [clang-diagnostic-error]
	edm::LogInfo("No CMSSW version set in database, accepting " PROJECT_VERSION);
                                                                                                            ^
note: expanded from here
```