Add a wrapper for cuda-gdb and package its support files
Set PYTHONHOME to scram's PYTHON_BASE to fix the error:

  Could not find platform independent libraries <prefix>
  Could not find platform dependent libraries <exec_prefix>
  Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
  ImportError: No module named site

Package $CUDA_BASE/share/gdb to fix the error:

  Python Exception <type 'exceptions.NameError'> Installation error:
  gdb.execute_unwinders function is missing: