[10.6.X] update tkonlinesw-fake to implement extra symbols
cmssw aarch64 IBs fails to build due to following issing symbols. This PR provides these symbols via tkonlnesw-fake package
```
  CalibrationHistosUsingDb.cc:(.text+0x828): undefined reference to `apvDescription::getIsha()'
   CalibrationHistosUsingDb.cc:(.text+0x850): undefined reference to `apvDescription::getVfs()'
```

https://github.com/cms-externals/tkonlinesw-fake/commit/97afe74471b299148ac9ccdea21e9cda961ec885