blackhat: fix compile on armv7hl
On armv7hl target integers in switch(..) expressions overflow, .e.g,

    case 0x0F02030908:
    case 0x0E02030908:

generates:

    warning: overflow in implicit constant conversion [-Woverflow]

and:

    error: duplicate case value
    error: previously used here

Change all 'long' to 'long long'. long is 4 bytes on armv7hl, but 8
bytes on x86_64. long long is 8 bytes on both platforms. Thus there
should be no changes on ABI level.

Signed-off-by: David Abdurachmanov <davidlt@cern.ch>