Change of gosam.spec
Since Herwig7 needs gosam_env.sh script which is not build via the Gosam tarball.
GoSam is now installed via the python installation script.

There is still a bug which is related to hardcoding the python path:
Error: Local path dependency found for external+gosam+2.0
  /afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300/20161206/q/slc6_amd64_gcc530/external/python/2.7.11-oenich/bin/python