py2-pycurl: make sure link-time ssl backend and compile-time match
Bump version to 7.43.0.

Add missing dependency on OpenSSL (pycurl includes headers if OpenSSL is
selected as backend).

We have noticed the following issue in GCC 5.3.0 branch:

    import pycurl
    ImportError: pycurl: libcurl link-time ssl backend (openssl) is
    different from compile-time ssl backend (none/other)

At compile time pycurl hardcoded the backend it's using:

    src/pycurl.h:#   define COMPILE_SSL_LIB "openssl"
    src/pycurl.h:#   define COMPILE_SSL_LIB "gnutls"
    src/pycurl.h:#   define COMPILE_SSL_LIB "nss"
    src/pycurl.h:#  define COMPILE_SSL_LIB "none/other"
    src/pycurl.h:# define COMPILE_SSL_LIB "none/other"

Then at run-time it queries cURL for fetures/configuration to check if
link-time [run-time] and compile-time SSL backends match. In our case it
didn't manage to figure SSL backend at compile-time.

We explicitly select that we are using OpenSSL.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>
(cherry picked from commit fa6650669a611df75230d02d98309d513642e55d)